version: "3"
name: rs-auth
services:
  db:
    image: "postgres:15.3-bookworm"
    container_name: rs_pg_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - rs_data:/var/lib/postgresql@15/data
volumes:
  rs_data:
